export const QUEUE_TRACK = 'QUEUE_TRACK';
export const UPDATE_QUEUE = 'UPDATE_QUEUE';
export const QUEUE_ENDED = 'QUEUE_ENDED';
export const QUEUE_REMOVE_TRACK = 'QUEUE_REMOVE_TRACK';

export const SEARCH_TRACKS = 'SEARCH_TRACKS';
export const SEARCH_TRACKS_SUCCESS = 'SEARCH_TRACKS_SUCCESS';
export const SEARCH_TRACKS_RESET = 'SEARCH_TRACKS_RESET';

export const FETCH_TRACK = 'FETCH_TRACK';
export const FETCH_TRACK_SUCCESS = 'FETCH_TRACK_SUCCESS';
export const FETCH_PLAYING_CONTEXT_SUCCESS = 'FETCH_PLAYING_CONTEXT_SUCCESS';

export const UPDATE_USERS = 'UPDATE_USERS';

export const LOAD = 'LOAD';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const PLAY_TRACK = 'PLAY_TRACK';
export const PLAY_TRACK_SUCCESS = 'PLAY_TRACK_SUCCESS';

export const MUTE_PLAYBACK = 'MUTE_PLAYBACK';
export const UNMUTE_PLAYBACK = 'UNMUTE_PLAYBACK';

export const FETCH_AVAILABLE_DEVICES = 'FETCH_AVAILABLE_DEVICES';
export const FETCH_AVAILABLE_DEVICES_SUCCESS = 'FETCH_AVAILABLE_DEVICES_SUCCESS';
export const FETCH_AVAILABLE_DEVICES_ERROR = 'FETCH_AVAILABLE_DEVICES_ERROR';

export const TRANSFER_PLAYBACK_TO_DEVICE = 'TRANSFER_PLAYBACK_TO_DEVICE';
export const TRANSFER_PLAYBACK_TO_DEVICE_SUCCESS = 'TRANSFER_PLAYBACK_TO_DEVICE_SUCCESS';
export const TRANSFER_PLAYBACK_TO_DEVICE_ERROR = 'TRANSFER_PLAYBACK_TO_DEVICE_ERROR';

export const VOTE_UP = 'VOTE_UP';
export const VOTE_UP_SUCCESS = 'VOTE_UP_SUCCESS';
